# Use an official Ruby runtime as a parent image
FROM ruby:2.7

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy Gemfile and Gemfile.lock to the container
COPY Gemfile Gemfile.lock ./

# Install dependencies using bundler
RUN bundle install

# Copy the current directory contents into the container
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the Rails application
CMD ["rails", "server", "-b", "0.0.0.0"]
Create another file named Dockerfile.db for the PostgreSQL container:

Dockerfile
Copy code
# Use the official PostgreSQL image as a parent image
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_USER Dikshita
ENV POSTGRES_PASSWORD railapp
ENV POSTGRES_DB railapp_db

# Expose port 5432 to the outside world
EXPOSE 5432