apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-app-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push
      taskRef:
        name: build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
resources:
  - name: rails-app-source
    type: git
  - name: rails-app-image
    type: image
    targetPath: /workspace/source
