apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: "my-argocd-instance"
  repositories: |
    - url: https://github.com/Dikshita008/my-argocd-config
      type: git
