apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-rails-app
    repoURL: https://github.com/your-username/my-argocd-config
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: repo-server
      app.kubernetes.io/part-of: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: repo-server
        app.kubernetes.io/part-of: argocd
    spec:
      containers:
      - name: repo-server
        image: argoproj/argocd-repo-server:v2.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/part-of: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/part-of: argocd
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:v2.0.1
