apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/my-argocd-config
    targetRevision: HEAD
    path: my-rails-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
